apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nginx-app
  template:
    metadata:
      labels:
        app: my-nginx-app
    spec:
      containers:
      - name: nginxweb
        image: oyodocacr.azurecr.io/snarendevops/docker:latest
        ports:
        - containerPort: 5000
      imagePullPolicy: Always
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-app-svc
spec:
  selector:
    app: my-nginx-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
